export default [
    {
        img:"./anime/one-piece-luffy-holding-hat-nazsl5hmss8bfb9n.jpg",
        name: ": One Piece",
        rating: ": 10/10",
        episodes: ": 1045",
        genre: ": Action, Comedy, Drama",
        storyline: ": A Boy from small town have a draam of beacamingthe king of priates he then goes to the sea searching for some crewmates and goes on multiple adventures in search of the one piece",
    },
    {
        img:"./bollywood/The_Family_Man.jpeg",
        name: ": Family Man",
        rating: ": 10/10",
        episodes: ": 19",
        seasons: ": 2",
        genre: ": Action, Comedy, Drama",
        storyline: ": The Family Man follows the story of Srikant Tiwari, who works as a senior officer in the Threat Analysis and Surveillance Cell (TASC), along with his best friend and colleague JK Talpade, which is a part of the National Investigation Agency (NIA) of India. The first season follows an investigation of a potential terrorist attack, ",
    },
    {
        img:"./bollywood/download.jpg",
        name: ": Mirzapur",
        rating: ": 10/10",
        episodes: ": 19",
        seasons: ": 2",
        genre: ": Action, Comedy, Drama",
        storyline: ": The iron-fisted Akhandanand Tripathi is a millionaire carpet exporter and the mafia don of Mirzapur. His son, Munna, is an unworthy, power-hungry heir who will stop at nothing to inherit his father's legacy. An incident at a wedding procession forces him to cross paths with Ramakant Pandit, an upstanding lawyer,",
    },
    {
        img:"./hollywood/download (20).jpg",
        name: ": Squid Game",
        rating: ": 8.0/10",
        episodes: ": 10",
        seasons: ": 1",
        genre: ": Mystery, Drama, Action",
        storyline: ":Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes. A survival game",
    },
    {
        img:"./anime/1116286.jpg",
        name: ": Jujtu kaisen",
        rating: ": 10/10",
        episodes: ": 30+",
        genre: ": Action, Comedy, supenatural",
        storyline: ": A high school kid with great strength had an encounter with a bad energy and meet a sorcerer who was protecting a finger of a very powerfull bad energy and to defeat the bad energy the boy eats the finger and then turns into a sorcerer trying to learn about the new powers",

    },
    {
        img:"./hollywood/download (12).jpg",
        name: ": Money Heist",
        rating: ": 8.2/10",
        episodes: ": 41",
        seasons: ": 5",
        genre: ": Drama, Mystery, Crime, Action",
        storyline: ":An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.",
    },
    {
        img:"./anime/A14950-1419814170.1366222610.jpg",
        name: ": Attack On Titan",
        rating: ": 10/10",
        episodes: ": 40+",
        genre: ": Action, mystry, supenatural",
        storyline: ": a great wall which protects the country from the titans which eats the human beings get broken by a titan and that titan along wth a group of other titans attack the village and one of the titan wats the mother of eren jieger who then joi  the milatry to kill all the titan and avenge his mother",

    },
    {
        img:"./bollywood/download (1).jpg",
        name: ": Matsya Kaand",
        rating: ": 8.9/10",
        episodes: ": 8",
        seasons: ": 1",
        genre: ": Action, Comedy, Drama,mystry",
        storyline: ": Matsya Thada (Ravii Dubey) is caught setting ablaze the petrol pump allotted to his mother after his army-man father loses his life in the Indo-Pak Kargil War. In prison, he finds a mentor in Anand Pandit (Piyush Mishra) who uses the Mahabharata teachings to prepare him for life outside prison after he completes his sentence. ",
    },
    {
        img:"./bollywood/download (3).jpg",
        name: ": College Romance",
        rating: ": 8.4/10",
        episodes: ": 15",
        seasons: ": 3",
        genre: ": Comedy, Drama, Romance",
        storyline: ": Three best friends look for love, laughs and some lifelong memories while attending college together. Some Are funny some are emotional and some are just weird the main characters of this story are a group of three best friends NIARA, TRIPPY, KARAN and their girlfirends and boyfriends",
    },
    {
        img:"./hollywood/download (11).jpg",
        name: ": Lucifer",
        rating: ": 8.1/10",
        episodes: ": 93",
        seasons: ": 5",
        genre: ": Drama, Mystery, Crime, Comedy",
        storyline: ":Lucifer Morningstar has decided he's had enough of being the dutiful servant in Hell and decides to spend some time on Earth to better understand humanity. He settles in Los Angeles",
    },
    {
        img:"./hollywood/download (9).jpg",
        name: ": Stranger Things",
        rating: ": 8.7/10",
        episodes: ": 42",
        seasons: ": 3",
        genre: ": Drama, Horror, Fantasy",
        storyline: ":When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.",
    },
    {
        img:"./hollywood/download (7).jpg",
        name: ": 1899",
        rating: ": 7.4/10",
        episodes: ": 8",
        seasons: ": 1",
        genre: ": Drama , Mystry",
        storyline: ": Multinational immigrants traveling from the old continent to the new encounter a nightmarish riddle aboard a second ship adrift on the open sea. ",
    },
    {
        img:"./anime/A6236-884031587.1484110754.jpg",
        name: ": Ginatama",
        rating: ": 10/10",
        episodes: ": 300+",
        genre: ": Action, Comedy",
        storyline: ": a country which was protected by samurai and  was know as a land of samurai was invaded by aliens and all the samurai tries to fight them and protect their country but they get defeated and due to that the samurai are no longer allowed to carry swords with them",

    },
    {
        img:"./anime/A16142-1330236887.1419219934.jpg",
        name: ": Assasination-Classroom",
        rating: ": 7/10",
        episodes: ": 30+",
        genre: ": Action, Comedy, supenatural",
        storyline: ": when th emoon explodes a person get supernatural power who threaterns the world that he will distory the whole world and every one on it and makes a demand to the governement that he wants to tech some stuedents who can try to assasinate him ",

    },
    {
        img:"./bollywood/download (6).jpg",
        name: ": Campus Diaries",
        rating: ": 8.9/10",
        episodes: ": 12",
        seasons: ": 1",
        genre: ": Comedy, Drama, Romance",
        storyline: ": Campus Diaries is a coming-of-age drama of six students at Excel University..",
    },
    {
        img:"./bollywood/download (7).jpg",
        name: ": Gullak",
        rating: ": 9.1/10",
        episodes: ": 15",
        seasons: ": 3",
        genre: ": Comedy, Drama, Family",
        storyline: ": Set in quaint by-lanes in the heart of India, Gullak is a collection of disarming and relatable tales of the Mishra family.",
    },
    {
        img:"./hollywood/download (5).jpg",
        name: ": The Big Bang Theory",
        rating: ": 8.2/10",
        episodes: ": 280",
        seasons: ": 15",
        genre: ": Comedy , Romance",
        storyline: ": A woman who moves into an apartment across the hall from two brilliant but socially awkward physicists shows them how little they know about life outside of the laboratory. ",
    },
    {
        img:"./anime/A16840-4113667313.1443583619.jpg",
        name: ": One Punch Man",
        rating: ": 10/10",
        episodes: ": 30+",
        genre: ": Action, Comedy, supenatural drama",
        storyline: ": in a world of heroes a guy named sitama who is super strong and can defeat any monster with just a punch joins the hero assosiation to earn some money where he meets genoes who is a cybord who wants to know the secret that why is he so much strong",

    },
    {
        img:"./hollywood/download (4).jpg",
        name: ": Friends",
        rating: ": 8.9/10",
        episodes: ": 235",
        seasons: ": 22",
        genre: ": Comedy, Romance",
        storyline: ": Follows the personal and professional lives of six twenty to thirty year-old friends living in the Manhattan borough of New York City. the story is about a group of crazy group of 6 friends who are best friends and each one have of them feel in love and do crazy stuff ",
    },
    {
        img:"./bollywood/download (8).jpg",
        name: ": Hostel Daze",
        rating: ": 8.5/10",
        episodes: ": 15",
        seasons: ": 3",
        genre: ": Comedy, Drama, ",
        storyline: ": Through the adventures of four friends 'Hostel Daze' captures what goes inside an engineering hostel in India.",
    },
    {
        img:"./bollywood/download (9).jpg",
        name: ": Kota Factory",
        rating: ": 9.1/10",
        episodes: ": 10",
        seasons: ": 2",
        genre: ": Comedy, Drama, ",
        storyline: ": Dedicated to Shrimati SL Loney ji, Shri Irodov ji and Maanniya HC Verma ji, 'Kota Factory' is TVF's latest original. India's first 'Black and White' show highlights the problems present day IIT-JEE aspirants face in their day-to-day lives.",
    },
    {
        img:"./anime/A24773-1205524557.1658671109.jpg",
        name: ": My Hero Accademiya",
        rating: ": 10/10",
        episodes: ": 100+",
        genre: ": Action, Comedy, supenatural",
        storyline: ": In a world full of heroes a university which trains the childerends born with a unique ability or power known as quriks are trained so that they can become heroes and help other people , the number one hero ALL MIGHT who is getting older meets Midoriya who do not have a quirk an dis very sad ",

    },
    {
        img:"./anime/key_art_naruto.webp",
        name: ": Naruto",
        rating: ": 10/10",
        episodes: ": 700+",
        genre: ": Action, Comedy, ninja",
        storyline: ": In a world of ninjas a boy who have a beast  who have nearly  infinite chakra known as tailed best has been sealed inside his body due to which very one in the town treats the boy as a monster an due to this the boy dreams of becoming hokage and he joins a ninja academy where he meets sakura , sasuke , kakashi and many different peoples",

    },
    {
        img:"./bollywood/download (20).jpg",
        name: ": Panchayat",
        rating: ": 8.9/10",
        episodes: ": 15",
        seasons: ": 2",
        genre: ": Drama,comedy",
        storyline: ": A comedy-drama, which captures the journey of an engineering graduate Abhishek, who for lack of a better job option joins as secretary of a Panchayat office in a remote village of Uttar Pradesh",
    },
    {
        img:"./hollywood/download (2).jpg",
        name: ": Legends Of Tomprrow",
        rating: ": 6.8/10",
        episodes: ": 110",
        seasons: ": 6",
        genre: ": Action, Adventure, Drama",
        storyline: ": Time-traveling rogue Rip Hunter must recruit a ragtag team of heroes and villains to help prevent an apocalypse that could impact not only Earth, but all of time. a bunch of rogue criminals are grouped together in order to fight crime in different time lines and make time line stable for all the human being",
    },
    {
        img:"./anime/kimetsunurie02.jpg",
        name: ": Demon Slayer",
        rating: ": 10/10",
        episodes: ": 50+",
        genre: ": Action, Comedy, supenatural, samurai, demons",
        storyline: ": In a small village where a poor family lives get attacked by demons who killes the whole family and only a boy and his sister who becomes a demon are left alive when th eboy comes back to te village he finds out about his family masacare and decides to become a demon slayer to find a way to turn his sister back to human ",

    },
    {
        img:"./hollywood/download (14).jpg",
        name: ": The Boys",
        rating: ": 8.7/10",
        episodes: ": 25",
        seasons: ": 3",
        genre: ": Action, Comedy, Crime",
        storyline: ": A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers. the main character of this story is WILLIAM BUTHER an HOMELANDER , homelander who is a cyschopath superhero rapes buthers wife and hide his wife in a safe house and buther wants to takes revenge from the homelander",
    },
]