export default [
    {
        img:"./bollywood/The_Family_Man.jpeg",
        name: ": Family Man",
        rating: ": 10/10",
        episodes: ": 19",
        seasons: ": 2",
        genre: ": Action, Comedy, Drama",
        storyline: ": The Family Man follows the story of Srikant Tiwari, who works as a senior officer in the Threat Analysis and Surveillance Cell (TASC), along with his best friend and colleague JK Talpade, which is a part of the National Investigation Agency (NIA) of India. The first season follows an investigation of a potential terrorist attack, ",
    },
    {
        img:"./bollywood/download.jpg",
        name: ": Mirzapur",
        rating: ": 10/10",
        episodes: ": 19",
        seasons: ": 2",
        genre: ": Action, Comedy, Drama",
        storyline: ": The iron-fisted Akhandanand Tripathi is a millionaire carpet exporter and the mafia don of Mirzapur. His son, Munna, is an unworthy, power-hungry heir who will stop at nothing to inherit his father's legacy. An incident at a wedding procession forces him to cross paths with Ramakant Pandit, an upstanding lawyer,",
    },
    {
        img:"./bollywood/download (1).jpg",
        name: ": Matsya Kaand",
        rating: ": 8.9/10",
        episodes: ": 8",
        seasons: ": 1",
        genre: ": Action, Comedy, Drama,mystry",
        storyline: ": Matsya Thada (Ravii Dubey) is caught setting ablaze the petrol pump allotted to his mother after his army-man father loses his life in the Indo-Pak Kargil War. In prison, he finds a mentor in Anand Pandit (Piyush Mishra) who uses the Mahabharata teachings to prepare him for life outside prison after he completes his sentence. ",
    },
    {
        img:"./bollywood/download (2).jpg",
        name: ": Tripling",
        rating: ": 8.5/10",
        episodes: ": 10",
        seasons: ": 2",
        genre: ": Comedy, Drama",
        storyline: ": Once upon a time, a beautiful baba, a madafaka and a Queen went on an unplanned road-trip. And then they did it again! What has changed between Chandan Chanchal and Chitvan in the past 6 months? Keep your eyes on the road as your favourite siblings are all set to re-unite for another adventure!",
    },
    {
        img:"./bollywood/download (3).jpg",
        name: ": College Romance",
        rating: ": 8.4/10",
        episodes: ": 15",
        seasons: ": 3",
        genre: ": Comedy, Drama, Romance",
        storyline: ": Three best friends look for love, laughs and some lifelong memories while attending college together. Some Are funny some are emotional and some are just weird the main characters of this story are a group of three best friends NIARA, TRIPPY, KARAN and their girlfirends and boyfriends",
    },
    {
        img:"./bollywood/download (4).jpg",
        name: ": Flames",
        rating: ": 8.9/10",
        episodes: ": 15",
        seasons: ": 3",
        genre: ": Comedy, Drama, Romance",
        storyline: ": A teenage romance from The Timeliners that aims straight from the heart. This web-series is the story of a young romance unfolding as a chemical reaction. th emain character of this story is a group of three best friends who fell in love in a coaching centre but not with with each other",
    },
    {
        img:"./bollywood/download (5).jpg",
        name: ": IM Mature",
        rating: ": 8.7/10",
        episodes: ": 10",
        seasons: ": 2",
        genre: ": Comedy, Drama, Romance",
        storyline: ": ImMATURE follows the lives of three teenage boys - Dhruv, Chacha and Chutney who are in their final year of high school. They deal with the everyday ups and downs of being a teenager, including friendships, first love, heartbreak, etc.",
    },
    {
        img:"./bollywood/download (6).jpg",
        name: ": Campus Diaries",
        rating: ": 8.9/10",
        episodes: ": 12",
        seasons: ": 1",
        genre: ": Comedy, Drama, Romance",
        storyline: ": Campus Diaries is a coming-of-age drama of six students at Excel University..",
    },
    {
        img:"./bollywood/download (7).jpg",
        name: ": Gullak",
        rating: ": 9.1/10",
        episodes: ": 15",
        seasons: ": 3",
        genre: ": Comedy, Drama, Family",
        storyline: ": Set in quaint by-lanes in the heart of India, Gullak is a collection of disarming and relatable tales of the Mishra family.",
    },
    {
        img:"./bollywood/download (8).jpg",
        name: ": Hostel Daze",
        rating: ": 8.5/10",
        episodes: ": 15",
        seasons: ": 3",
        genre: ": Comedy, Drama, ",
        storyline: ": Through the adventures of four friends 'Hostel Daze' captures what goes inside an engineering hostel in India.",
    },
    {
        img:"./bollywood/download (9).jpg",
        name: ": Kota Factory",
        rating: ": 9.1/10",
        episodes: ": 10",
        seasons: ": 2",
        genre: ": Comedy, Drama, ",
        storyline: ": Dedicated to Shrimati SL Loney ji, Shri Irodov ji and Maanniya HC Verma ji, 'Kota Factory' is TVF's latest original. India's first 'Black and White' show highlights the problems present day IIT-JEE aspirants face in their day-to-day lives.",
    },
    {
        img:"./bollywood/download (10).jpg",
        name: ": Pitchers",
        rating: ": 8.5/10",
        episodes: ": 16",
        seasons: ": 2",
        genre: ": Comedy, Drama, ",
        storyline: ": A story of trials and tribulations of four young entrepreneurs who quit their day jobs in order to pursue their start up venture.",
    },
    {
        img:"./bollywood/download (11).jpg",
        name: ": Indori Ishq",
        rating: ": 6.9/10",
        episodes: ": 9",
        seasons: ": 1",
        genre: ": Comedy, Drama, ",
        storyline: ": The story begins with amusing attempts of twelfth-grader, Kunal, to woo his classmate, Tara. Kunal finally manages to propose to Tara and their love story begins. After his schooling, Kunal leaves Indore and moves to Mumbai to join a Naval College. Soon his sober life turns upside-down when Tara dumps him for someone else",
    },
    {
        img:"./bollywood/download (12).jpg",
        name: ": Sacred Games",
        rating: ": 8.5/10",
        episodes: ": 16",
        seasons: ": 2",
        genre: ": Comedy, Drama, ",
        storyline: ": A link in their pasts leads an honest cop to a fugitive gang boss, whose cryptic warning spurs the officer on a quest to save Mumbai from cataclysm.",
    },
    {
        img:"./bollywood/download (13).jpg",
        name: ": Tandav",
        rating: ": 8.5/10",
        episodes: ": 15",
        seasons: ": 1",
        genre: ": Drama,Thriller ",
        storyline: ": Tandav is a story that happens in the capital city of the world's largest democracy - DILLI (New Delhi), where it takes you inside the closed, chaotic doors of power and manipulation and uncover the darkest lanes of Indian politics",
    },
    {
        img:"./bollywood/download (15).jpg",
        name: ": Dhindora",
        rating: ": 8.8/10",
        episodes: ": 8",
        seasons: ": 1",
        genre: ": Drama,comedy",
        storyline: ": It revolves around Bhuvan and his family's everyday lives, when an unexpected purchase leads to a series of events and depicts every common man's larger than life dreams",
    },
    {
        img:"./bollywood/download (20).jpg",
        name: ": Panchayat",
        rating: ": 8.9/10",
        episodes: ": 15",
        seasons: ": 2",
        genre: ": Drama,comedy",
        storyline: ": A comedy-drama, which captures the journey of an engineering graduate Abhishek, who for lack of a better job option joins as secretary of a Panchayat office in a remote village of Uttar Pradesh",
    },
    {
        img:"./bollywood/download (14).jpg",
        name: ": Apharan",
        rating: ": 8.3/10",
        episodes: ": 23",
        seasons: ": 2",
        genre: ": Action,Comedy, Crime, Thriller",
        storyline: ": Rudra, a senior police inspector is set on a mission to catch a wanted criminal with his personal life on stake",
    },
]