export default[
    {
        img:"./hollywood/download (14).jpg",
        name: ": The Boys",
        rating: ": 8.7/10",
        episodes: ": 25",
        seasons: ": 3",
        genre: ": Action, Comedy, Crime",
        storyline: ": A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers. the main character of this story is WILLIAM BUTHER an HOMELANDER , homelander who is a cyschopath superhero rapes buthers wife and hide his wife in a safe house and buther wants to takes revenge from the homelander",
    },
    {
        img:"./hollywood/download (1).jpg",
        name: ": Arrow",
        rating: ": 7.5/10",
        episodes: ": 170",
        seasons: ": 7",
        genre: ": Action, Adventure, Crime",
        storyline: ": Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilanty and fights crime",
    },
    {
        img:"./hollywood/images.jpg",
        name: ": Supergirl",
        rating: ": 6.2/10",
        episodes: ": 126",
        seasons: ": 7",
        genre: ": Action, Adventure, Crime",
        storyline: ": The adventures of Superman's cousin and her own superhero career. When superman comes to earth from his home planet his cousin was also sent to earth but due to the time difference his cousin arrives late and clart kent aka superman alerady was a hero of eath so there was no need of another superman",
    },
    {
        img:"./hollywood/download (2).jpg",
        name: ": Legends Of Tomprrow",
        rating: ": 6.8/10",
        episodes: ": 110",
        seasons: ": 6",
        genre: ": Action, Adventure, Drama",
        storyline: ": Time-traveling rogue Rip Hunter must recruit a ragtag team of heroes and villains to help prevent an apocalypse that could impact not only Earth, but all of time. a bunch of rogue criminals are grouped together in order to fight crime in different time lines and make time line stable for all the human being",
    },
    {
        img:"./hollywood/download (3).jpg",
        name: ": Allice In Borderland",
        rating: ": 7.6/10",
        episodes: ": 16",
        seasons: ": 2",
        genre: ": Action, Adventure, Drama",
        storyline: ": A group of bored delinquents are transported to a parallel dimension as part of a survival game. they play multiple differen tgames in order to survive and those who lose the game or refuses to play game are killed or they die while playing on the game",
    },
    {
        img:"./hollywood/download (4).jpg",
        name: ": Friends",
        rating: ": 8.9/10",
        episodes: ": 235",
        seasons: ": 22",
        genre: ": Comedy, Romance",
        storyline: ": Follows the personal and professional lives of six twenty to thirty year-old friends living in the Manhattan borough of New York City. the story is about a group of crazy group of 6 friends who are best friends and each one have of them feel in love and do crazy stuff ",
    },
    {
        img:"./hollywood/download (5).jpg",
        name: ": The Big Bang Theory",
        rating: ": 8.2/10",
        episodes: ": 280",
        seasons: ": 15",
        genre: ": Comedy , Romance",
        storyline: ": A woman who moves into an apartment across the hall from two brilliant but socially awkward physicists shows them how little they know about life outside of the laboratory. ",
    },
    {
        img:"./hollywood/download (6).jpg",
        name: ": Brooklyn Nine Nine",
        rating: ": 8.4/10",
        episodes: ": 153",
        seasons: ": 9",
        genre: ": Comedy , Romance,Crime",
        storyline: ": Comedy series following the exploits of Det. Jake Peralta and his diverse, lovable colleagues as they police the NYPD's 99th Precinct. ",
    },
    {
        img:"./hollywood/download (7).jpg",
        name: ": 1899",
        rating: ": 7.4/10",
        episodes: ": 8",
        seasons: ": 1",
        genre: ": Drama , Mystry",
        storyline: ": Multinational immigrants traveling from the old continent to the new encounter a nightmarish riddle aboard a second ship adrift on the open sea. ",
    },
    {
        img:"./hollywood/download (8).jpg",
        name: ": Dark",
        rating: ": 8.7/10",
        episodes: ": 26",
        seasons: ": 3",
        genre: ": Crime,Drama , Mystry",
        storyline: ":A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four families.",
    },
    {
        img:"./hollywood/download (9).jpg",
        name: ": Stranger Things",
        rating: ": 8.7/10",
        episodes: ": 42",
        seasons: ": 3",
        genre: ": Drama, Horror, Fantasy",
        storyline: ":When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.",
    },
    {
        img:"./hollywood/download (10).jpg",
        name: ": The 100",
        rating: ": 7.6/10",
        episodes: ": 100",
        seasons: ": 6",
        genre: ": Drama, Mystery, Sci-Fi",
        storyline: ":Set 97 years after a nuclear war destroyed civilization, when a spaceship housing humanity's lone survivors sends 100 juvenile delinquents back to Earth, hoping to repopulate the planet.",
    },
    {
        img:"./hollywood/download (11).jpg",
        name: ": Lucifer",
        rating: ": 8.1/10",
        episodes: ": 93",
        seasons: ": 5",
        genre: ": Drama, Mystery, Crime, Comedy",
        storyline: ":Lucifer Morningstar has decided he's had enough of being the dutiful servant in Hell and decides to spend some time on Earth to better understand humanity. He settles in Los Angeles",
    },
    {
        img:"./hollywood/download (12).jpg",
        name: ": Money Heist",
        rating: ": 8.2/10",
        episodes: ": 41",
        seasons: ": 5",
        genre: ": Drama, Mystery, Crime, Action",
        storyline: ":An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.",
    },
    {
        img:"./hollywood/download (13).jpg",
        name: ": Loki",
        rating: ": 8.2/10",
        episodes: ": 12",
        seasons: ": 1",
        genre: ": Fantasy, Adevnture, Action",
        storyline: ":The mercurial villain Loki resumes his role as the God of Mischief in a new series that takes place after the events of “Avengers: Endgame.",
    },
    {
        img:"./hollywood/download (16).jpg",
        name: ": Hawkeye",
        rating: ": 7.5/10",
        episodes: ": 6",
        seasons: ": 1",
        genre: ": Crime, Adevnture, Action",
        storyline: ":Series based on the Marvel Comics superhero Hawkeye, centering on the adventures of Young Avenger, Kate Bishop, who took on the role after the original Avenger, Clint Barton.",
    },
    {
        img:"./hollywood/download (17).jpg",
        name: ": What If",
        rating: ": 7.4/10",
        episodes: ": 19",
        seasons: ": 2",
        genre: ": Crime, Adevnture, Action",
        storyline: ":Exploring pivotal moments from the Marvel Cinematic Universe and turning them on their head, leading the audience into uncharted territory.",
    },
    {
        img:"./hollywood/download (18).jpg",
        name: ": She-Hulk: Attorney At Law",
        rating: ": 5.2/10",
        episodes: ": 9",
        seasons: ": 1",
        genre: ": Comedy, Adevnture, Action",
        storyline: ":Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered Hulk.",
    },
    {
        img:"./hollywood/download (19).jpg",
        name: ": The Umbrella Academy",
        rating: ": 7.9/10",
        episodes: ": 31",
        seasons: ": 3",
        genre: ": Comedy, Adevnture, Action",
        storyline: ":A family of former child heroes, now grown apart, must reunite to continue to protect the world. Here number 5 who is one the main hero in the umbrella academy has the ability to time travel and he jumps back itno time says that the world is going to end in 3 ays and same thing hapens again and again and there actions causes accoployspse",
    },
    {
        img:"./hollywood/download (20).jpg",
        name: ": Squid Game",
        rating: ": 8.0/10",
        episodes: ": 10",
        seasons: ": 1",
        genre: ": Mystery, Drama, Action",
        storyline: ":Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes. A survival game",
    },
    {
        img:"./hollywood/download (21).jpg",
        name: ": Wednesday",
        rating: ": 8.3/10",
        episodes: ": 8",
        seasons: ": 1",
        genre: ": Comedy,Crime,Fantasy",
        storyline: ":Follows Wednesday Addams' years as a student, when she attempts to master her emerging psychic ability, thwart and solve the mystery that embroiled her parents",
    },
    {
        img:"./hollywood/download (22).jpg",
        name: ": How I Meet Your Mother",
        rating: ": 8.3/10",
        episodes: ": 208",
        seasons: ": 10",
        genre: ": Comedy,Romance",
        storyline: ":A father recounts to his children - through a series of flashbacks - the journey he and his four best friends took leading up to him meeting their mother.",
    },
]
